--- # ----------- CONFIGURABLE START -----------
title: "Sebastiaan (Bas) Ammerlaan — bariton"
description: "Website van klassiek zanger Sebastiaan Ammerlaan."
url: https://bammerlaan.nl # Site url, without a slash at the end.
signoff: "Sebastiaan Ammerlaan" # Your name
facebook_appid: # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-77407217-1
share: false # Turn on twitter and facebook share buttons
email: "bas@bammerlaan.nl"
timezone: "Europe/Amsterdam"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# ------------ CONFIGURABLE END ------------

permalink: /posts/:title
defaults:
  - values:
      layout: "default"

staticman:
  api: "https://staticman3.herokuapp.com/v3/entry/github/bammerlaan/bammerlaan.github.io/master/comments"
  path: "_data/comments/{{ page.lang-ref }}"
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
